# Generated by Django 3.2.4 on 2021-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_usermodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
