# Generated by Django 3.2.4 on 2021-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210707_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
