# Generated by Django 3.1.3 on 2021-07-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_usermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
