# Generated by Django 3.1.3 on 2021-07-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0004_auto_20210709_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='User county'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, verbose_name='Post index'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
