# Generated by Django 3.1.3 on 2021-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210710_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='activation_link',
            field=models.TextField(blank=True),
        ),
    ]
